export const projectTechnologies = {
  ford_otosan: [
    "center",

    "ml-dl-node",
    "center-ml-dl-edge",

    "backend-node",
    "center-backend-edge",
    
    "databases-node",
    "center-databases-edge",
    
    "dev-data-mlops-node",
    "center-dev-data-mlops-edge",

    "cloud-node",
    "center-cloud-edge",

    "soft-skills-node",
    "center-softskills-edge",

    "tensorflow",
    "ml-dl-tensorflow-edge",

    "keras",
    "ml-dl-keras-edge",

    "rnns",
    "ml-dl-rnns-edge",

    "transfer-learning",
    "ml-dl-transfer-learning-edge",

    "anomaly-detection",
    "ml-dl-anomaly-detection-edge",

    "pandas",
    "ml-dl-pandas-edge",

    "flask",
    "backend-flask-edge",

    "elk-stack",
    "databases-elk-stack-edge",

    "airflow",
    "dev-data-mlops-airflow-edge",

    "kafka",
    "dev-data-mlops-kafka-edge",

    "etl",
    "dev-data-mlops-etl-edge",

    "git",
    "dev-data-mlops-git-edge",

    "mlflow",
    "dev-data-mlops-mlflow-edge",

    "docker",
    "dev-data-mlops-docker-edge",

    "kubernetes",
    "dev-data-mlops-kubernetes-edge",

    "grafana",
    "dev-data-mlops-grafana-edge",

    "slack",
    "soft-skills-slack-edge",

    "agile",  
    "soft-skills-agile-edge"
],
  tai_internship: [
    "center",

    "ml-dl-node",
    "center-ml-dl-edge",
    "pandas",
    "ml-dl-pandas-edge",
    "transfer-learning",
    "ml-dl-transfer-learning-edge",
    "huggingface",
    "ml-dl-huggingface-edge",

    "backend-node",
    "center-backend-edge",
    "postman",
    "backend-postman-edge",

    "databases-node",
    "center-databases-edge",

    "dev-data-mlops-node",
    "center-dev-data-mlops-edge",
  
    "docker",
    "dev-data-mlops-docker-edge",
    "git",
    "dev-data-mlops-git-edge",
      
    "databases-mysql-edge",
    "mysql",

    "soft-skills-node",
    "center-softskills-edge",

    "doors",
    "soft-skills-doors-edge",
    "scrum",
    "soft-skills-scrum-edge",
  ],

  vigilant: [
    "center",

    "ml-dl-node",
    "center-ml-dl-edge",
    "tensorflow",
    "ml-dl-tensorflow-edge",
    "opencv",
    "ml-dl-opencv-edge",
    "fine-tuning",
    "ml-dl-fine-tuning-edge",
    "computer-vision",
    "ml-dl-computer-vision-edge",
    "keras",
    "ml-dl-keras-edge",
    "pandas",
    "ml-dl-pandas-edge",

    "backend-node",
    "center-backend-edge",
    "django",
    "backend-django-edge",
    "postman",
    "backend-postman-edge",
    "flask",
    "backend-flask-edge",
    "jinja2",
    "backend-jinja2-edge",

    "frontend-node",
    "center-frontend-edge",
    "reactjs",
    "frontend-reactjs-edge",
    "figma",
    "frontend-figma-edge",
    "tailwind",
    "frontend-tailwind-edge",

    "databases-node",
    "center-databases-edge",
    "firebase",
    "databases-firebase-edge",
    "mysql",
    "databases-mysql-edge",

    "dev-data-mlops-node",
    "center-dev-data-mlops-edge",
    "docker",
    "dev-data-mlops-docker-edge",
    "etl",
    "dev-data-mlops-etl-edge",
    "github-actions",
    "dev-data-mlops-github-actions-edge",
    "git",
    "dev-data-mlops-git-edge",



    "soft-skills-node",
    "center-softskills-edge",

    "slack",
    "soft-skills-slack-edge",
    "jira",
    "soft-skills-jira-edge",

  ],

  pneumonia_detection: [
    "center",

    "ml-dl-node",
    "center-ml-dl-edge",
    "pytorch",
    "ml-dl-pytorch-edge",
    "computer-vision",
    "ml-dl-computer-vision-edge",
    "opencv",
    "ml-dl-opencv-edge",
    "cnns",
    "ml-dl-cnns-edge",
    "scikit-learn",
    "ml-dl-scikit-learn-edge",
    "pandas",
    "ml-dl-pandas-edge",
    "transfer-learning",
    "ml-dl-transfer-learning-edge",

    "backend-node",
    "center-backend-edge",
    "streamlit",
    "backend-streamlit-edge",
    
    "cloud-node",
    "center-cloud-edge",
    "sagemaker",
    "cloud-sagemaker-edge",

    "databases-node",
    "center-databases-edge",
    "rds",
    "databases-rds-edge",
    
    "dev-data-mlops-node",
    "center-dev-data-mlops-edge",
    "git",
    "dev-data-mlops-git-edge",
    "docker",
    "dev-data-mlops-docker-edge",
    "etl",
    "dev-data-mlops-etl-edge",

    "soft-skills-node",
    "center-softskills-edge",
    "slack",
    "soft-skills-slack-edge",
    "scrum",
    "soft-skills-scrum-edge",
  ],

  airpreneurs: [
    "center",

    "ml-dl-node",
    "center-ml-dl-edge",
    "tensorflow",
    "ml-dl-tensorflow-edge",
    "pandas",
    "ml-dl-pandas-edge",

    "backend-node",
    "center-backend-edge",
    "postman",
    "backend-postman-edge",
    "fastapi",
    "backend-fastapi-edge",

    "frontend-node",
    "center-frontend-edge",
    "reactjs",
    "frontend-reactjs-edge",
    "figma",
    "frontend-figma-edge",
    "bootstrap",
    "frontend-bootstrap-edge",

    "databases-node",
    "center-databases-edge",
    "rds",
    "databases-rds-edge",
    
    "dev-data-mlops-node",
    "center-dev-data-mlops-edge",
    "docker",
    "dev-data-mlops-docker-edge",
    "git",
    "dev-data-mlops-git-edge",

    "cloud-node",
    "center-cloud-edge",
    "s3",
    "cloud-s3-edge",
    "ec2",
    "cloud-ec2-edge",
    "lambda",
    "cloud-lambda-edge",

    "soft-skills-node",
    "center-softskills-edge",
    "slack",
    "soft-skills-slack-edge",
  ],

  blockchain_project: [
    "center",

    "ml-dl-node",
    "center-ml-dl-edge",

    "backend-node",
    "center-backend-edge",

    "frontend-node",
    "center-frontend-edge",

    "databases-node",
    "center-databases-edge",
    
    "dev-data-mlops-node",
    "center-dev-data-mlops-edge",

    "cloud-node",
    "center-cloud-edge",

    "soft-skills-node",
    "center-softskills-edge",
  ],

  scraper_trading_project: [
    "center",

    "ml-dl-node",
    "center-ml-dl-edge",
    "rnns",
    "ml-dl-rnns-edge",
    "pandas",
    "ml-dl-pandas-edge",
    "transfer-learning",
    "ml-dl-transfer-learning-edge",
    "huggingface",
    "ml-dl-huggingface-edge",
    "fine-tuning",
    "ml-dl-fine-tuning-edge",
    "scikit-learn",
    "ml-dl-scikit-learn-edge",
    "kaggle",
    "ml-dl-kaggle-edge",

    "backend-node",
    "center-backend-edge",
    "restapi",
    "backend-restapi-edge",

    "databases-node",
    "center-databases-edge",
    "elk-stack",
    "databases-elk-stack-edge",

    "dev-data-mlops-node",
    "center-dev-data-mlops-edge",
    "git",
    "dev-data-mlops-git-edge",
    "docker",
    "dev-data-mlops-docker-edge",
    "etl",
    "dev-data-mlops-etl-edge",
    "kubernetes",
    "dev-data-mlops-kubernetes-edge",

  ],

  ar_app_project: [
    "center",

    "ml-dl-node",
    "center-ml-dl-edge",

    "backend-node",
    "center-backend-edge",

    "frontend-node",
    "center-frontend-edge",

    "databases-node",
    "center-databases-edge",
    
    "dev-data-mlops-node",
    "center-dev-data-mlops-edge",

    "cloud-node",
    "center-cloud-edge",

    "soft-skills-node",
    "center-softskills-edge",
  ],

  opengl_project: [
    "center",

    "ml-dl-node",
    "center-ml-dl-edge",

    "backend-node",
    "center-backend-edge",

    "frontend-node",
    "center-frontend-edge",

    "databases-node",
    "center-databases-edge",
    
    "dev-data-mlops-node",
    "center-dev-data-mlops-edge",

    "cloud-node",
    "center-cloud-edge",

    "soft-skills-node",
    "center-softskills-edge",
  ],

  erasmus_tracking_system: [
    "center",

    "backend-node",
    "center-backend-edge",
    "django",
    "backend-django-edge",
    "jinja2",
    "backend-jinja2-edge",

    "frontend-node",
    "center-frontend-edge",
    "figma",
    "frontend-figma-edge",

    "databases-node",
    "center-databases-edge",
    "mongodb",
    "databases-mongodb-edge",
    
    "dev-data-mlops-node",
    "center-dev-data-mlops-edge",
    "git",
    "dev-data-mlops-git-edge",

    "soft-skills-node",
    "center-softskills-edge",
    "jira",
    "soft-skills-jira-edge",
  ],

  nlp_projects: [
    "center",

    "ml-dl-node",
    "center-ml-dl-edge",
    "pytorch",
    "ml-dl-pytorch-edge",
    "tensorflow",
    "ml-dl-tensorflow-edge",
    "transformers",
    "ml-dl-transformers-edge",
    "transfer-learning",
    "ml-dl-transfer-learning-edge",
    "llama",
    "ml-dl-llama-edge",
    "quantization",
    "ml-dl-quantization-edge",
    "anomaly-detection",
    "ml-dl-anomaly-detection-edge",
    "gpt",
    "ml-dl-gpt-edge",
    "mistral",
    "ml-dl-mistral-edge",
    "lora",
    "ml-dl-lora-edge",
    "huggingface",
    "ml-dl-huggingface-edge",
    "pandas",
    "ml-dl-pandas-edge",
    "rnns",
    "ml-dl-rnns-edge",
    "bert",
    "ml-dl-bert-edge",
    "opencv",
    "ml-dl-opencv-edge",
    "scikit-learn",
    "ml-dl-scikit-learn-edge",
    "xgboost",
    "ml-dl-xgboost-edge",
    
    "backend-node",
    "center-backend-edge",
    "fastapi",
    "backend-fastapi-edge",
    "graphql",
    "backend-graphql-edge",
    "django",
    "backend-django-edge",
    "streamlit",
    "backend-streamlit-edge",
    "postman",
    "backend-postman-edge",
    "flask",
    "backend-flask-edge",
    "restapi",
    "backend-restapi-edge",


    "frontend-node",
    "center-frontend-edge",
    "tailwind",
    "frontend-tailwind-edge",
    "reactjs",
    "frontend-reactjs-edge",

    "databases-node",
    "center-databases-edge",
    "mongodb",
    "databases-mongodb-edge",
    "cassandra",
    "databases-cassandra-edge",
    "postgresql",
    "databases-postgresql-edge",
    "mysql",
    "databases-mysql-edge",
    "rds",
    "databases-rds-edge",
    "elk-stack",
    "databases-elk-stack-edge",
    
    "dev-data-mlops-node",
    "center-dev-data-mlops-edge",
    "groq",
    "dev-data-mlops-groq-edge",
    "etl",
    "dev-data-mlops-etl-edge",
    "dvc",
    "dev-data-mlops-dvc-edge",
    "nvidia-nim",
    "dev-data-mlops-nvidia-nim-edge",
    "github-actions",
    "dev-data-mlops-github-actions-edge",
    "docker",
    "dev-data-mlops-docker-edge",
    "kafka",
    "dev-data-mlops-kafka-edge",
    "lpu",
    "dev-data-mlops-lpu-edge",
    "mlflow",
    "dev-data-mlops-mlflow-edge",
    "grafana",
    "dev-data-mlops-grafana-edge",
    "git",
    "dev-data-mlops-git-edge",
    "airflow",
    "dev-data-mlops-airflow-edge",
    "dagshub",
    "dev-data-mlops-dagshub-edge",
    "circleci",
    "dev-data-mlops-circleci-edge",

    "cloud-node",
    "center-cloud-edge",
    "bedrock",
    "cloud-bedrock-edge",
    "sagemaker",
    "cloud-sagemaker-edge",
    "lambda",
    "cloud-lambda-edge",
    "ec2",
    "cloud-ec2-edge",
    "s3", 
    "cloud-s3-edge",
    "api-gateway",
    "cloud-api-gateway-edge",

    "soft-skills-node",
    "center-softskills-edge",
  ],

  ml_projects: [
    "center",

    "ml-dl-node",
    "center-ml-dl-edge",
    "pytorch",
    "ml-dl-pytorch-edge",
    "tensorflow",
    "ml-dl-tensorflow-edge",
    "transformers",
    "ml-dl-transformers-edge",
    "transfer-learning",
    "ml-dl-transfer-learning-edge",
    "llama",
    "ml-dl-llama-edge",
    "quantization",
    "ml-dl-quantization-edge",
    "anomaly-detection",
    "ml-dl-anomaly-detection-edge",
    "gpt",
    "ml-dl-gpt-edge",
    "mistral",
    "ml-dl-mistral-edge",
    "lora",
    "ml-dl-lora-edge",
    "huggingface",
    "ml-dl-huggingface-edge",
    "pandas",
    "ml-dl-pandas-edge",
    "rnns",
    "ml-dl-rnns-edge",
    "bert",
    "ml-dl-bert-edge",
    "opencv",
    "ml-dl-opencv-edge",
    "scikit-learn",
    "ml-dl-scikit-learn-edge",
    "xgboost",
    "ml-dl-xgboost-edge",
    
    "backend-node",
    "center-backend-edge",
    "fastapi",
    "backend-fastapi-edge",
    "graphql",
    "backend-graphql-edge",
    "django",
    "backend-django-edge",
    "streamlit",
    "backend-streamlit-edge",
    "postman",
    "backend-postman-edge",
    "flask",
    "backend-flask-edge",
    "restapi",
    "backend-restapi-edge",


    "frontend-node",
    "center-frontend-edge",
    "tailwind",
    "frontend-tailwind-edge",
    "reactjs",
    "frontend-reactjs-edge",

    "databases-node",
    "center-databases-edge",
    "mongodb",
    "databases-mongodb-edge",
    "cassandra",
    "databases-cassandra-edge",
    "postgresql",
    "databases-postgresql-edge",
    "mysql",
    "databases-mysql-edge",
    "rds",
    "databases-rds-edge",
    "elk-stack",
    "databases-elk-stack-edge",
    
    "dev-data-mlops-node",
    "center-dev-data-mlops-edge",
    "groq",
    "dev-data-mlops-groq-edge",
    "etl",
    "dev-data-mlops-etl-edge",
    "dvc",
    "dev-data-mlops-dvc-edge",
    "nvidia-nim",
    "dev-data-mlops-nvidia-nim-edge",
    "github-actions",
    "dev-data-mlops-github-actions-edge",
    "docker",
    "dev-data-mlops-docker-edge",
    "kafka",
    "dev-data-mlops-kafka-edge",
    "lpu",
    "dev-data-mlops-lpu-edge",
    "mlflow",
    "dev-data-mlops-mlflow-edge",
    "grafana",
    "dev-data-mlops-grafana-edge",
    "git",
    "dev-data-mlops-git-edge",
    "airflow",
    "dev-data-mlops-airflow-edge",
    "dagshub",
    "dev-data-mlops-dagshub-edge",
    "circleci",
    "dev-data-mlops-circleci-edge",

    "cloud-node",
    "center-cloud-edge",
    "bedrock",
    "cloud-bedrock-edge",
    "sagemaker",
    "cloud-sagemaker-edge",
    "lambda",
    "cloud-lambda-edge",
    "ec2",
    "cloud-ec2-edge",
    "s3", 
    "cloud-s3-edge",
    "api-gateway",
    "cloud-api-gateway-edge",

    "soft-skills-node",
    "center-softskills-edge",
  ],


  about_me: [
    // Nodes
    "about-me",
    "education",
    "hobies",

    // Education-related nodes
    "bilkent-university",
    "izmir-science-highschool",

    "gaming",
    "serieses",
    "pc-building",

    "about-me-education",
    "about-me-hobies",
    "education-izmir-science-highschool",
    "education-bilkent-university",
    "hobies-gaming",
    "hobies-serieses",
    "hobies-pc-building",
  ],

  about_me_paragraph: ["about-me"],

  education: [
    "about-me",
    "education",
    "bilkent-university",
    "izmir-science-highschool",
    "about-me-education",
    "education-izmir-science-highschool",
    "education-bilkent-university",
  ],

  hobies: [
    "about-me",
    "about-me-hobies",
    "hobies",
    "gaming",
    "serieses",
    "pc-building",
    "hobies-gaming",
    "hobies-serieses",
    "hobies-pc-building",
  ],

certifications_header: [
    "certifications",
    "certifications-header",
    "certifications-deep-learning-header",
    "certifications-google-header",
    "certifications-meta-header",
    "certifications-duke-header",
    "certifications-ibm-header",
    "certifications-kaggle-header",
    "certifications-udemy-header", // Added Udemy header
    "deep-learning",
    "ml-specialization",
    "tensorflow-cert",
    "cybersecurity",
    "data-analysis",
    "project-management",
    "frontend-meta",
    "backend-meta",
    "git-docker-cert",
    "eda-cert",
    "kaggle-cert",
    "genai-hf-langchain", // New Udemy Certification
    "mlops-bootcamp", // New Udemy Certification
    "deep-learning-header",
    "google-header",
    "meta-header",
    "duke-header",
    "ibm-header",
    "kaggle-header",
    "udemy-header", // Added Udemy Header
    "deep-learning-header-deep-learning",
    "deep-learning-header-ml-specialization",
    "deep-learning-header-tensorflow-cert",
    "google-header-cybersecurity",
    "google-header-data-analysis",
    "google-header-project-management",
    "meta-header-frontend-meta",
    "meta-header-backend-meta",
    "duke-header-git-docker-cert",
    "ibm-header-eda-cert",
    "kaggle-header-kaggle-cert",
    "udemy-header-genai-hf-langchain", // Added Udemy Certification
    "udemy-header-mlops-bootcamp", // Added Udemy Certification,
    "kaggle-header-kaggle-cert-intro",
    "kaggle-header-kaggle-cert-pandas",
    "kaggle-header-kaggle-cert-feature",
    "kaggle-header-kaggle-cert-visualization",
    "kaggle-cert-intro",
    "kaggle-cert-pandas",
    "kaggle-cert-feature",
    "kaggle-cert-visualization",
    "duke-header-devops-cert",
    "duke-header-docker-cert",
    "duke-header-git-cert",
    "devops-cert",
    "docker-cert",
    "git-cert",
  ],

  deep_learning: [
    "certifications",
    "certifications-header",
    "certifications-deep-learning-header",
    "deep-learning-header",
    "deep-learning-header-deep-learning",
    "deep-learning-header-ml-specialization",
    "deep-learning-header-tensorflow-cert",
    "deep-learning",
    "ml-specialization",
    "tensorflow-cert",
  ],

  google_certificates: [
    "certifications",
    "certifications-header",
    "certifications-google-header",
    "google-header",
    "google-header-cybersecurity",
    "google-header-data-analysis",
    "google-header-project-management",
    "cybersecurity",
    "data-analysis",
    "project-management",
  ],

  backend_frontend_meta: [
    "certifications",
    "certifications-header",
    "certifications-meta-header",
    "meta-header",
    "meta-header-frontend-meta",
    "meta-header-backend-meta",
    "frontend-meta",
    "backend-meta",
  ],

  git_docker_devops: [
    "certifications",
    "certifications-header",
    "certifications-duke-header",
    "duke-header",
    "duke-header-git-docker-cert",
    "git-docker-cert",
    "duke-header-devops-cert",
    "duke-header-docker-cert",
    "duke-header-git-cert",
    "devops-cert",
    "docker-cert",
    "git-cert",
  ],

  eda_ibm: [
    "certifications",
    "certifications-header",
    "certifications-ibm-header",
    "ibm-header",
    "ibm-header-eda-cert",
    "eda-cert",
  ],

  kaggle_certificates: [
    "certifications",
    "certifications-header",
    "certifications-kaggle-header",
    "kaggle-header",
    "kaggle-header-kaggle-cert",
    "kaggle-cert",
    "kaggle-header-kaggle-cert-intro",
    "kaggle-header-kaggle-cert-pandas",
    "kaggle-header-kaggle-cert-feature",
    "kaggle-header-kaggle-cert-visualization",
    "kaggle-cert-intro",
    "kaggle-cert-pandas",
    "kaggle-cert-feature",
    "kaggle-cert-visualization",
  ],

  udemy_certificates: [ // New Udemy section
    "certifications",
    "certifications-header",
    "certifications-udemy-header",
    "udemy-header",
    "udemy-header-genai-hf-langchain",
    "udemy-header-mlops-bootcamp",
    "genai-hf-langchain",
    "mlops-bootcamp",
  ]
};
